version: '3'

services:

  elasticsearch:
    #build: elasticsearch/
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch-elk:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.type=unpooled"
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #mem_limit: 4g
    deploy:
        mode: global
    networks:
      - elk

  logstash:
    #build: logstash/
    image: docker.elastic.co/logstash/logstash:5.4.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /data/logstash/logs:/usr/share/logstash/logs
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    #build: kibana/
    image: docker.elastic.co/kibana/kibana:5.4.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: overlay
volumes:
  elasticsearch-elk:
